export const RESET_STATE = 'RESET_STATE';
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED';
// Auth
export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const LOGOUT = 'LOGOUT';

export const START_REGISTER = 'START_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const FAILED_REGISTER = 'FAILED_REGISTER';

// Users
export const START_FETCH_USER_PROFILE_INFO = 'START_FETCH_USER_PROFILE_INFO';
export const SUCCESS_FETCH_USER_PROFILE_INFO = 'SUCCESS_FETCH_USER_PROFILE_INFO';
export const FAILED_FETCH_USER_PROFILE_INFO = 'FAILED_FETCH_USER_PROFILE_INFO';

// Posts
export const START_FETCH_POSTS = 'START_FETCH_POSTS';
export const SUCCESS_FETCH_POSTS = 'SUCCESS_FETCH_POSTS';
export const FAILED_FETCH_POSTS = 'FAILED_FETCH_POSTS';

export const START_PUBLISH_POST = 'START_PUBLISH_POST';
export const SUCCESS_PUBLISH_POST = 'SUCCESS_PUBLISH_POST';
export const FAILED_PUBLISH_POST = 'FAILED_PUBLISH_POST';

