export const RESET_STATE = 'RESET_STATE';
// Auth
export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const LOGIN_REQUEST_COMPLETED = 'LOGIN_REQUEST_COMPLETED';
export const LOGOUT = 'LOGOUT';

export const START_REGISTER = 'START_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const FAILED_REGISTER = 'FAILED_REGISTER';
export const REGISTER_REQUEST_COMPLETED = 'REGISTER_REQUEST_COMPLETED';

// Users
export const START_FETCH_USER_PROFILE_INFO = 'START_FETCH_USER_PROFILE_INFO';
export const SUCCESS_FETCH_USER_PROFILE_INFO = 'SUCCESS_FETCH_USER_PROFILE_INFO';
export const FAILED_FETCH_USER_PROFILE_INFO = 'FAILED_FETCH_USER_PROFILE_INFO';
export const FETCH_USER_PROFILE_INFO_REQUEST_COMPLETED = 'FETCH_USER_PROFILE_INFO_REQUEST_COMPLETED';

export const START_UPDATE_USER_PROFILE_INFO = 'START_UPDATE_USER_PROFILE_INFO';
export const SUCCESS_UPDATE_USER_PROFILE_INFO = 'SUCCESS_UPDATE_USER_PROFILE_INFO';
export const FAILED_UPDATE_USER_PROFILE_INFO = 'FAILED_UPDATE_USER_PROFILE_INFO';
export const UPDATE_USER_PROFILE_INFO_REQUEST_COMPLETED = 'UPDATE_USER_PROFILE_INFO_REQUEST_COMPLETED';

export const START_SEARCH_USERS = 'START_SEARCH_USERS';
export const SUCCESS_SEARCH_USERS = 'SUCCESS_SEARCH_USERS';
export const FAILED_SEARCH_USERS = 'FAILED_SEARCH_USERS';
export const SEARCH_USERS_REQUEST_COMPLETED = 'SEARCH_USERS_REQUEST_COMPLETED';

// Posts
export const START_FETCH_POSTS = 'START_FETCH_POSTS';
export const SUCCESS_FETCH_POSTS = 'SUCCESS_FETCH_POSTS';
export const FAILED_FETCH_POSTS = 'FAILED_FETCH_POSTS';
export const FETCH_POSTS_REQUEST_COMPLETED = 'FETCH_POSTS_REQUEST_COMPLETED';

export const START_PUBLISH_POST = 'START_PUBLISH_POST';
export const SUCCESS_PUBLISH_POST = 'SUCCESS_PUBLISH_POST';
export const FAILED_PUBLISH_POST = 'FAILED_PUBLISH_POST';
export const PUBLISH_POST_REQUEST_COMPLETED = 'PUBLISH_POST_REQUEST_COMPLETED';

// Friends
export const START_FETCH_USER_FRIENDS = 'START_FETCH_USER_FRIENDS';
export const SUCCESS_FETCH_USER_FRIENDS = 'SUCCESS_FETCH_USER_FRIENDS';
export const FAILED_FETCH_USER_FRIENDS = 'FAILED_FETCH_USER_FRIENDS';
export const FETCH_USER_FRIENDS_REQUEST_COMPLETED = 'FETCH_USER_FRIENDS_REQUEST_COMPLETED';

export const START_ADD_USER_TO_FRIENDS = 'START_ADD_USER_TO_FRIENDS';
export const SUCCESS_ADD_USER_TO_FRIENDS = 'SUCCESS_ADD_USER_TO_FRIENDS';
export const FAILED_ADD_USER_TO_FRIENDS = 'FAILED_ADD_USER_TO_FRIENDS';
export const ADD_USER_TO_FRIENDS_REQUEST_COMPLETED = 'ADD_USER_TO_FRIENDS_REQUEST_COMPLETED';

export const START_USER_UNFRIEND = 'START_USER_UNFRIEND';
export const SUCCESS_USER_UNFRIEND = 'SUCCESS_USER_UNFRIEND';
export const FAILED_USER_UNFRIEND = 'FAILED_USER_UNFRIEND';
export const USER_UNFRIEND_REQUEST_COMPLETED = 'USER_UNFRIEND_REQUEST_COMPLETED';
